// Local image assets
export const images = {
  logo: "/images/logo.png",
  rectangle161124867: "/images/rectangle161124867.png",
  rectangle161124865: "/images/rectangle161124865.png",
  rectangle161124858: "/images/rectangle161124858.png",
  rectangle1: "/images/rectangle1.png",
  union: "/images/union.png",
  frame: "/images/frame.png",
  instagramLogo: "/images/instagramLogo.png",
  facebook: "/images/facebook.png",
  youtube: "/images/youtube.png",
  tiktok: "/images/tiktok.png",
  homesCom: "/images/homesCom.png",
  realtorCom: "/images/realtorCom.png",
  zillow: "/images/zillow.png",
  redfin: "/images/redfin.png",
  instagramLogo2: "/images/instagramLogo2.png",
  frame2: "/images/frame2.png",
  aiIcon: "/images/aiIcon.png",
  googleLogo: "/images/googleLogo.png",
  zillowIcon: "/images/zillowIcon.png",
};
